---
- name: clean-up installer mess
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - "/etc/cloud/cloud.cfg.d/99-installer.cfg"
  - "/etc/cloud/cloud.cfg.d/curtin-preserve-sources.cfg"
  - "/etc/cloud/cloud.cfg.d/subiquity-disable-cloudinit-networking.cfg"
