---
- name: install cloud-init and extra packages 
  apt:
    name: [cloud-init, curl]
    state: latest 

- name: distro specific cloud-init mods
  include_tasks: cloud-init-{{ansible_distribution_release }}.yaml
