---
- name: install cloud-init and extra packages
  apt:
    name: [cloud-init, curl]
    state: latest

- name: Include distro-specific cloud-init mods (with fallback)
  include_tasks: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "cloud-init-{{ ansible_distribution_release }}.yaml"
        - "cloud-init-default.yaml"
      paths:
        - "{{ role_path }}/tasks"


- name: Create fedcloud config
  copy:
    content: |
      # EGI FedCloud configuration

      # Make sure to disable ssh password authentication
      ssh_pwauth: 0

      # In OpenNebula, use network based datasource,
      # so that it can successfully resolve IPv4 based hostname
      datasource:
        OpenNebula:
            dsmode: net
    dest: /etc/cloud/cloud.cfg.d/01_fedcloud.cfg
