---
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Python requirements.txt
  - package-ecosystem: "pip"
    directory: "/builder"
    schedule:
      interval: "weekly"
