---
- name: install epel 
  yum:
    name: epel-release
    state: latest 
  when: ansible_distribution_major_version != "8"

- name: install cloud-init and extra packages 
  yum:
    name: [cloud-init, cloud-utils-growpart]
    state: latest 

- name: Create fedcloud config
  copy:
    content: |
      # EGI FedCloud configuration
      
      # Make sure to disable ssh password authentication
      ssh_pwauth: 0
      # Regenerate keys
      ssh_deletekeys: True
      ssh_genkeytypes: ['rsa', 'dsa']
    dest: /etc/cloud/cloud.cfg.d/01_fedcloud.cfg

- name: enable service 
  service: 
    name: "{{ item }}"
    enabled: yes
  loop:
    - cloud-init-local
    - cloud-init
    - cloud-config
    - cloud-final
