- hosts: all
  gather_facts: False
  tasks:
  - name: install python
    raw: test -e /usr/bin/python || test -e /usr/bin/python3 || (yum install -y python39)

- hosts: all
  tasks:
  - name: update packages
    yum:
      name: '*'
      state: latest 
  - name: get the rpm package facts
    package_facts:
      manager: "auto"
  - name: Rebuilding initramfs for kernel 
    command: |
       dracut -f --no-hostonly /boot/initramfs-{{ item['version'] }}-{{ item['release'] }}.{{ item['arch'] }}.img
                {{ item['version'] }}-{{ item['release'] }}.{{ item['arch'] }} 
    loop: "{{ ansible_facts.packages['kernel'] }}"
