- hosts: all
  roles:
  - cloud-init
  - role: grycap.docker
    vars:
      docker_version: "5:20.10.12~3-0~{{ansible_distribution | lower}}-{{ansible_distribution_release}}"
      docker_compose_version: 1.29.2
      docker_install_pip: false
  - role: appliance
    vars:
      appliance_tag: "sha-aa9ef01"
      ssm_tag: "2.4.1-1"
  - cleanup
