---
- hosts: all
  become: true
  roles:
    - cloud-init

- hosts: all
  become: true
  tasks:
    - name: Install oneclient
      shell: |
        # Install oneclient from the available script
        curl -sS http://get.onedata.org/oneclient.sh | bash
    - name: Setup the datahub directory
      ansible.builtin.file:
        path: /mnt/datahub
        state: directory
        mode: '0777'
        owner: 1000
    - name: Allow other for fuse
      ansible.builtin.lineinfile:
        path: /etc/fuse.conf
        regexp: '^user_allow_other'
        line: user_allow_other
    - name: mount helper
      copy:
        dest: /home/ubuntu/mount.sh
        mode: '0755'
        owner: 1000
        content: |
          #!/bin/bash

          # Personal token obtained from https://datahub.eu
          ONECLIENT_ACCESS_TOKEN="<your DataHub token>"
          # Closesr oneprovider supporting your spaces
          ONECLIENT_PROVIDER_HOST="plg-cyfronet-01.datahub.egi.eu"

          # mount with allow_other so jovyan can access
          oneclient -H "$ONECLIENT_PROVIDER_HOST" -t "$ONECLIENT_ACCESS_TOKEN"  -o allow_other /mnt/datahub
    - name: umount helper
      copy:
        dest: /home/ubuntu/umount.sh
        mode: '0755'
        owner: 1000
        content: |
          #!/bin/bash

          oneclient -u /mnt/datahub
    - name: Add a jovyan user without sudo
      user:
        name: jovyan
        comment: Jupyter user
        shell: /bin/bash
        uid: 1002
    - name: create datahub directory as link
      ansible.builtin.file:
        dest: /home/jovyan/datahub
        src: /mnt/datahub
        state: link
        mode: '0755'
    - name: Install micromamba
      shell: |
        wget -qO- https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
        mv bin/micromamba /usr/local/bin/micromamba
    - name: install packages
      ansible.builtin.apt:
        name: [nginx, acl]
        state: present

# set things up as jovyan
- hosts: all
  become: true
  become_user: jovyan
  tasks:
    - name: create micromamba directory
      ansible.builtin.file:
        path: /home/jovyan/micromamba
        state: directory
        mode: '0755'
    - name: Install jupyterhub using conda
      shell: |
        micromamba install -y -c conda-forge -p /home/jovyan/micromamba jupyter jupyterlab jq
    - name: Get micromamba env
      shell: |
        micromamba shell init --shell=bash --prefix=/home/jovyan/micromamba || true

- hosts: all
  become: true
  tasks:
    - name: Create jupyter unit
      copy:
        dest: /etc/systemd/system/jupyter.service
        content: |
          [Unit]
          Description=Jupyter Notebook

          [Service]
          Type=simple
          PIDFile=/run/jupyter.pid
          WorkingDirectory=/home/jovyan
          ExecStart=/home/jovyan/micromamba/bin/jupyter-lab --no-browser --notebook-dir=/home/jovyan
          User=jovyan
          Group=jovyan
          Restart=always
          RestartSec=10

          [Install]
          WantedBy=multi-user.target
    - name: Enable jupyter
      ansible.builtin.systemd:
        state: started
        enabled: yes
        name: jupyter
        daemon_reload: yes
    - name: Reconfig nginx
      copy:
        dest: /etc/nginx/sites-available/default
        content:
          server {
            listen 80 default_server;
            listen [::]:80 default_server;

            root /var/www/html;

            index index.html index.htm index.nginx-debian.html;

            server_name _;

            location / {
                proxy_pass http://127.0.0.1:8888/;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                proxy_set_header Host $host;
                proxy_read_timeout 86400;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
          }

- hosts: all
  become: true
  roles:
    - cleanup
