---
- hosts: all
  become: true
  gather_facts: False
  tasks:
    - name: install python
      raw: test -e /usr/bin/python || (apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y python-minimal || DEBIAN_FRONTEND=noninteractive apt-get install -y python3-minimal)

- hosts: all
  become: true
  tasks:
    - name: update packages
      apt: upgrade=dist

- hosts: all
  become: true
  tasks:
    - name: Put skel files into ubuntu's home
      copy:
        remote_src: true
        src: /etc/skel/
        dest: /home/ubuntu/
        owner: ubuntu
