#cloud-config
---
users:
  - name: egi
    gecos: EGI
    primary_group: egi
    groups: users
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_import_id:
      - gh:enolfc
      - gh:gwarf
      - gh:sebastian-luna-valero

packages:
  - git
  - jq
  - retry
  - qemu-system-x86
  - qemu-utils
  - python3-venv
  - python3-dev
  - python3-openstackclient
  - ansible
  - build-essential

write_files:
  - content: |
      #!/bin/sh
      set -e

      mkdir -p /var/tmp/egi
      cd /var/tmp/egi || exit

      # Valid GitHub token to access the repo
      COMMIT_SHA="%REF%"
      IMAGE="%IMAGE%"
      FEDCLOUD_LOCKER_TOKEN="%FEDCLOUD_LOCKER_TOKEN%"
      UPLOAD="%UPLOAD%"

      # get the repo code and untar at cwd
      curl -L -H "Accept: application/vnd.github.v3+raw" \
              "https://api.github.com/repos/EGI-Federation/fedcloud-vmi-templates/tarball/$COMMIT_SHA" | \
              tar xz --strip=1

      # install external galaxy roles
      ansible-galaxy role install -p /var/tmp/egi/ubuntu/provisioners/roles/ grycap.docker

      # build image
      builder/build-image.sh "$IMAGE" "$FEDCLOUD_LOCKER_TOKEN" "$UPLOAD" > /var/log/image-build.log 2>&1
    path: /var/lib/cloud/scripts/per-boot/build.sh
    permissions: '0755'
  - content: |
      #!/bin/sh
      mkdir -p /var/tmp/egi
      VM_ID="$(cloud-init query instance_id)"

      cloud-init status --wait
      cloud-init status >"/var/tmp/egi/$VM_ID"
      [ -f /var/log/image-build.log ] && \
          cat /var/log/image-build.log >>"/var/tmp/egi/$VM_ID"
      export PATH="/var/tmp/egi/.venv/bin:$PATH"
      # try 10 times, otherwise just die
      /var/tmp/egi/builder/refresh.sh cloud.egi.eu \
                                      "$(cat /var/tmp/egi/.refresh_token)" \
                                      backend
      OS_TOKEN="$(yq -r '.clouds.backend.auth.token' \
                  /etc/openstack/clouds.yaml)"
      retry -t 25 -d 200 -- openstack --os-cloud backend \
                                      --os-token "$OS_TOKEN" \
                                      object create --name "$VM_ID" \
                                      fedcloud-vmi "/var/tmp/egi/$VM_ID"
    path: /usr/local/bin/notify.sh
    permissions: '0755'
  - content: |
      [Unit]
      Description=Notify the github action

      [Service]
      ExecStart=/usr/local/bin/notify.sh

      [Install]
      WantedBy=multi-user.target
    path: /etc/systemd/system/notify.service
