---
- name: install requirements
  apt:
    name:
      # this is to make the nfs-based volumes work
      - nfs-common
    state: latest

- name: Configure docker
  include_role:
    name: grycap.docker
  vars:
    docker_version: "5:27.2.1-1~ubuntu.22.04~jammy"
    docker_compose_version: "v2.29.3"
    docker_install_pip: false
    docker_config_values:
      exec-opts:
        - native.cgroupdriver=systemd
      log-driver: json-file
      log-opts:
        max-size: 100m
      storage-driver: overlay2
      mtu: 1376

- name: Add docker group
  group:
    name: docker
    state: present

- name: Configure cloud-init to add docker group to ubuntu
  copy:
    content: |
      # Add the docker group to default user
      system_info:
         default_user:
           groups: [adm, audio, cdrom, dialout, dip, floppy, lxd, netdev, plugdev, sudo, video, docker]
    dest: /etc/cloud/cloud.cfg.d/02_docker.cfg

- name: Add repo key
  get_url:
    url: "https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key"
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc

- name: Add kubernetes repo
  apt_repository:
    repo: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /'
    state: present
    update_cache: yes

- name: Install kubernetes packages
  vars:
    kube_version: 1.30.5-1.1
  apt:
    name:
      - "kubelet={{ kube_version }}"
      - "kubeadm={{ kube_version }}"
      - "kubectl={{ kube_version }}"
    state: present
