---
name: "Build changed images"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  image-list:
    name: build images
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.change-list.outputs.changed_files }}

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          # full git history needed to get proper list of changed files
          fetch-depth: 0
      - name: Get list of changes
        id: change-list
        run: |
          CHANGES=()
          for f in $(git diff --name-only \
                     "${{ github.event.pull_request.base.sha }}" \
                     | grep "\.hcl$")
          do
            [ -e "$f" ] || continue
            CHANGES+=("$f")
          done
          echo "changed_files=$(jq -nc '$ARGS.positional' --args "${CHANGES[@]}")" >>"$GITHUB_OUTPUT"
  build:
    needs: image-list
    if: ${{ needs.image-list.outputs.changes != '[]' && needs.image-list.outputs.changes != '' }}
    uses: ./.github/workflows/build.yml
    with:
      images: ${{ needs.image-list.outputs.changes }}
      upload: ${{ github.event_name == 'push' }}
    secrets: inherit
